#!/bin/sh
DUMP_SCHEDULE=${SCHEDULE:-daily}

case $DUMP_SCHEDULE in
  hourly)
    cp /usr/local/bin/dump /etc/periodic/hourly/
    ;;
  daily)
    cp /usr/local/bin/dump /etc/periodic/daily/
    ;;
  weekly)
    cp /usr/local/bin/dump /etc/periodic/weekly/
    ;;
  *) 
    echo "$DUMP_SCHEDULE /usr/local/bin/dump" >> /etc/crontabs/root
    ;;
esac

exec /usr/sbin/crond -f -L /var/log/crond.log
