#!/bin/sh
DUMP_SCHEDULE=${SCHEDULE:-daily}

case $DUMP_SCHEDULE in
  hourly)
    mv /etc/backup /etc/periodic/hourly/
    ;;
  daily)
    mv /etc/backup /etc/periodic/daily/
    ;;
  weekly)
    mv /etc/backup /etc/periodic/weekly/
    ;;
  *) 
    echo "$DUMP_SCHEDULE /etc/backup" >> /etc/crontabs/root
    ;;
esac

exec /usr/sbin/crond -f -L /var/log/crond.log
